# Generated by Django 4.0 on 2021-12-28 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_text_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
