# Generated by Django 4.0 on 2021-12-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articles_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40, verbose_name='تگ')),
                ('article', models.ManyToManyField(to='articles.Articles')),
            ],
            options={
                'verbose_name': 'لیست تگ',
                'verbose_name_plural': 'تگ',
            },
        ),
    ]
