# Generated by Django 4.0 on 2021-12-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagorizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagorizes', models.CharField(max_length=40, verbose_name='تگ')),
            ],
            options={
                'verbose_name': ' دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.catagorizes'),
        ),
    ]
