# Generated by Django 4.0 on 2021-12-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_catagorizes_articles_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='article',
            new_name='catagorize',
        ),
    ]
