# Generated by Django 4.0 on 2022-01-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'نظرات', 'verbose_name_plural': 'نظر'},
        ),
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='articles.articles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
