# Generated by Django 4.0 on 2022-01-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_comments_options_comments_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.PROTECT, to='articles.articles'),
        ),
    ]
