# Generated by Django 4.0 on 2022-01-08 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_comments_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
